# -*- coding: utf-8 -*-
"""activity22_10_2022.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CPc_xt-Tl7i0RbNLuSXLdEui0M6CCdmn
"""

name=input("Enter name")
print('வணக்கம்', name)
print("your user name is", name)

name=input("Enter name")
number=input("Enter number")
print('வணக்கம்', number, name)
print("your user name is", number, name)

name=input("Enter name")
amount=input("Enter amount")
print('வணக்கம்', name, 'தங்களுக்கு நான் தரவேண்டிய தொகை', amount)
print("உங்களது பயனர் பெயர்", name, 'தங்களுக்குச் செலுத்தப்பெற்ற தொகை',amount)