# -*- coding: utf-8 -*-
"""type_python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1omp_7cZh2BJPOVsY5TevMOVbL_R6ANHu
"""

print(type(1))

print(type(32.3))

print(type(True))

print(type("வணக்கம்"))